spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/afg_db_dev
#    url: jdbc:postgresql://localhost:5432/afg_db
#    url: jdbc:postgresql://192.168.50.7:5416/af_guard_db
#    url: jdbc:postgresql://localhost:5416/af_guard_db
    username: afg_app
    password: 3211
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        generate_statistics: true
server:
  port: 9001



#  logging:
#    level:
#      org.hibernate.SQL: OFF
#      org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF


